In [1]:
import pandas as pd  
import numpy as np 
from sklearn import preprocessing

In [2]:
dataset = pd.read_csv(r"F:\Annie\Cornell MS\MetaSUB\Book1.csv")  
dataset.columns
dataset[~dataset.isin([np.nan, np.inf, -np.inf]).any(1)]

Unnamed: 0  Acetoanaerobium sticklandii  \
0    haib17CEM4890_H75CGCCXY_SL263637                            0   
1    haib17CEM4890_H75CGCCXY_SL263638                            0   
2    haib17CEM4890_H75CGCCXY_SL263649                            0   
3    haib17CEM4890_H75CGCCXY_SL263650                            0   
4    haib17CEM4890_H75CGCCXY_SL263661                            0   
5    haib17CEM4890_H75CGCCXY_SL263662                            0   
6    haib17CEM4890_H75CGCCXY_SL263673                            0   
7    haib17CEM4890_H75CGCCXY_SL263674                            0   
8    haib17CEM4890_H75CGCCXY_SL263685                            0   
9    haib17CEM4890_H75CGCCXY_SL263686                            0   
10   haib17CEM4890_H75CGCCXY_SL263697                            0   
11   haib17CEM4890_H75CGCCXY_SL263709                            0   
12    haib17DB4959_HMCMJCCXY_SL336155                            0   
13    haib17DB4959_HMCMJCCXY_SL336156                            0   
14    haib17DB4959_HMCMJCCXY_SL336157                            0   
15    haib17DB4959_HMCMJCCXY_SL336159                            0   
16    haib17DB4959_HMCMJCCXY_SL336160                            0   
17    haib17DB4959_HMCMJCCXY_SL336161                            0   
18    haib17DB4959_HMCMJCCXY_SL336162                            0   
19    haib17DB4959_HMCMJCCXY_SL336163                            0   
20    haib17DB4959_HMCMJCCXY_SL336164                            0   
21    haib17DB4959_HMCMJCCXY_SL336165                            0   
22   haib17CEM4890_H7KYMCCXY_SL273032                            0   
23   haib17CEM4890_H7KYMCCXY_SL273033                            0   
24   haib17CEM4890_H7KYMCCXY_SL273041                            0   
25   haib17CEM4890_H7KYMCCXY_SL273042                            0   
26   haib17CEM4890_H7KYMCCXY_SL273043                            0   
27   haib17CEM4890_H7KYMCCXY_SL273044                            0   
28   haib17CEM4890_H7KYMCCXY_SL273045                            0   
29   haib17CEM4890_H7KYMCCXY_SL273052                            0   
..                                ...                          ...   
969  haib17CEM5106_HCCGHCCXY_SL270570                            0   
970  haib17CEM5106_HCCGHCCXY_SL270571                            0   
971  haib17CEM5106_HCCGHCCXY_SL270572                            0   
972  haib17CEM5106_HCCGHCCXY_SL270573                            0   
973  haib17CEM5106_HCCGHCCXY_SL270574                            0   
974  haib17CEM5106_HCCGHCCXY_SL270575                            0   
975  haib17CEM5106_HCCGHCCXY_SL270576                            0   
976  haib17CEM5106_HCCGHCCXY_SL270577                            0   
977  haib17CEM5106_HCCGHCCXY_SL270578                            0   
978  haib17CEM5106_HCCGHCCXY_SL270579                            0   
979  haib17CEM5106_HCCGHCCXY_SL270580                            0   
980  haib17CEM5106_HCCGHCCXY_SL270581                            0   
981  haib17CEM5106_HCCGHCCXY_SL270582                            0   
982  haib17CEM5106_HCCGHCCXY_SL270583                            0   
983  haib17CEM5106_HCCGHCCXY_SL270584                            0   
984  haib17CEM5106_HCCGHCCXY_SL270585                            0   
985  haib17CEM5106_HCCGHCCXY_SL270586                            0   
986  haib17CEM5106_HCCGHCCXY_SL270587                            0   
987  haib17CEM5106_HCCGHCCXY_SL270588                            0   
988  haib17CEM5106_HCY5HCCXY_SL270903                            0   
989  haib17CEM5106_HCY5HCCXY_SL270904                            0   
990  haib17CEM5106_HCY5HCCXY_SL270906                            0   
991  haib17CEM5106_HCY5HCCXY_SL270907                            0   
992  haib17CEM5106_HCY5HCCXY_SL270908                            0   
993  haib17CEM5106_HCY5HCCXY_SL270909                            0   
994  haib17CEM5106_HCY5HCCXY_SL270910

In [3]:
X = dataset.iloc[:, 1:-1].values  
y = dataset.iloc[:, 2840].values 
print (X[1])
print (y[1])

[0 0 0 ... 0 0 0]
1


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Chandrima\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=200, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test)  

In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred.round()))  
print(classification_report(y_test,y_pred.round()))  
print(accuracy_score(y_test, y_pred.round()))  

[[ 0  0  1  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3  2  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  3  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  1  1  0  1  0  1  0  0]
 [ 0  0  0  0  0  1  1  2  2  1  0  0  0  0]
 [ 0  0  0  0  1  0  1  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  3 70  5  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  5 14 22 39]]
             precision    recall  f1-score   support

          1       0.00      0.00      0.00         2
          2       0.00      0.00      0.00         1
          3       0.00      0.00      0.00         8
          4       0.00      0.00      0.00         1
          5       0.17      1.00      0.29         1
          6       0.25      0.20      0.22        

C:\Users\Chandrima\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
